-- MySQL Script generated by MySQL Workbench
-- Mon Jul  4 22:15:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`condominio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`condominio` (
  `nif` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`condominio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`condominio` (
  `nif` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documento` (
  `documento` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  `tipoPagamento` VARCHAR(45) NULL,
  `Total` VARCHAR(45) NULL,
  `condominio_nif` INT NOT NULL,
  PRIMARY KEY (`documento`, `condominio_nif`),
  INDEX `fk_documento_condominio1_idx` (`condominio_nif` ASC),
  CONSTRAINT `fk_documento_condominio1`
    FOREIGN KEY (`condominio_nif`)
    REFERENCES `mydb`.`condominio` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipoDocumento` (
  `tipoDoc` INT NOT NULL,
  `fracao` VARCHAR(45) NULL,
  `localizacao` VARCHAR(45) NULL,
  PRIMARY KEY (`tipoDoc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recibo` (
  `dataDoc` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `valorMensal` VARCHAR(45) NULL,
  `documento_documento` INT NOT NULL,
  `tipoDocumento_tipoDoc` INT NOT NULL,
  PRIMARY KEY (`dataDoc`, `documento_documento`, `tipoDocumento_tipoDoc`),
  INDEX `fk_recibo_documento_idx` (`documento_documento` ASC),
  INDEX `fk_recibo_tipoDocumento1_idx` (`tipoDocumento_tipoDoc` ASC),
  CONSTRAINT `fk_recibo_documento`
    FOREIGN KEY (`documento_documento`)
    REFERENCES `mydb`.`documento` (`documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recibo_tipoDocumento1`
    FOREIGN KEY (`tipoDocumento_tipoDoc`)
    REFERENCES `mydb`.`tipoDocumento` (`tipoDoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
